# Generated by Django 3.2.12 on 2022-05-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptech', '0002_make'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Make',
        ),
    ]
