# Generated by Django 3.2.12 on 2022-05-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptech', '0003_delete_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
