# Generated by Django 3.2.12 on 2022-05-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
